# Generated by Django 4.0.2 on 2022-02-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('estagiario', 'Estagiário'), ('diretor', 'Diretor'), ('avaliador', 'Avaliador')], max_length=15),
        ),
    ]
