# Generated by Django 4.0.2 on 2022-02-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usuario_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(4, 'Avaliador'), (3, 'Diretor'), (2, 'Estagiário'), (1, 'Administrador')], default=1),
        ),
    ]
