# Generated by Django 4.0.2 on 2022-03-15 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reeducando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do reeducando')),
                ('rgc', models.CharField(max_length=200, verbose_name='Nº do RGC')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Digite seu nome')),
                ('email', models.EmailField(max_length=200, verbose_name='Digite seu email')),
                ('nivel', models.CharField(choices=[(0, 'Administrador'), (1, 'Estagiário'), (2, 'Diretor'), (3, 'Avaliador')], max_length=1)),
                ('senha', models.CharField(max_length=200, verbose_name='Digite a senha')),
            ],
        ),
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('arquivo', models.FilePathField()),
                ('reeducando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.reeducando')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_conteudo', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota conteudo')),
                ('nota_estrutura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota estrutura')),
                ('nota_ortografia', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota otografia')),
                ('status', models.CharField(max_length=200, verbose_name='Status')),
                ('comentario', models.CharField(max_length=200, verbose_name='Comentário')),
                ('resumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.resumo')),
            ],
        ),
    ]
