# Generated by Django 4.0.2 on 2022-03-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumo',
            name='titulo',
            field=models.CharField(default='titulo', max_length=200, verbose_name='Título do resumo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(4, 'Avaliador'), (3, 'Diretor'), (2, 'Estagiário'), (1, 'Administrador')], default=1),
        ),
    ]
